"""
PDF Generator Service
Generates enterprise-quality PDF reports using reportlab.
"""
import io
import logging
from datetime import datetime
from typing import Dict, Any, List

try:
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        PageBreak, Image, KeepTogether
    )
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False
    logger = logging.getLogger(__name__)
    logger.warning("reportlab not installed. PDF generation will not be available.")


logger = logging.getLogger(__name__)


class PDFGeneratorService:
    """Service for generating PDF reports"""
    
    @staticmethod
    def _add_header(canvas, doc, report_data: Dict[str, Any]):
        """Add header to each page"""
        canvas.saveState()
        canvas.setFont('Helvetica-Bold', 10)
        canvas.drawString(inch, 10.5 * inch, "AgentCraft Enterprise Report")
        canvas.setFont('Helvetica', 8)
        canvas.drawString(inch, 10.3 * inch, f"Report ID: {report_data['id']}")
        canvas.drawRightString(7.5 * inch, 10.5 * inch, report_data['templateName'])
        canvas.drawRightString(7.5 * inch, 10.3 * inch, datetime.now().strftime("%Y-%m-%d %H:%M"))
        canvas.line(inch, 10.2 * inch, 7.5 * inch, 10.2 * inch)
        canvas.restoreState()
    
    @staticmethod
    def _add_footer(canvas, doc, report_data: Dict[str, Any]):
        """Add footer to each page"""
        canvas.saveState()
        canvas.setFont('Helvetica', 7)
        canvas.setFillGray(0.5)
        canvas.drawString(inch, 0.5 * inch, f"Digital Fingerprint: {report_data['audit']['digitalFingerprint']}")
        canvas.drawRightString(7.5 * inch, 0.5 * inch, f"Page {doc.page}")
        canvas.line(inch, 0.6 * inch, 7.5 * inch, 0.6 * inch)
        canvas.setFillGray(0.3)
        canvas.drawCentredString(4.25 * inch, 0.3 * inch, "Generated by AgentCraft AI | Confidential")
        canvas.restoreState()
    
    @staticmethod
    def generate_pdf(report_data: Dict[str, Any]) -> bytes:
        """
        Generate PDF from report data.
        
        Args:
            report_data: Complete report data structure
            
        Returns:
            PDF bytes
        """
        if not REPORTLAB_AVAILABLE:
            raise RuntimeError("reportlab library not installed. Cannot generate PDF.")
        
        logger.info(f"Generating PDF for report {report_data['id']}")
        
        # Create PDF buffer
        buffer = io.BytesIO()
        
        # Create document
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=inch,
            leftMargin=inch,
            topMargin=1.2 * inch,
            bottomMargin=0.8 * inch,
            title=f"{report_data['templateName']} - {report_data['id']}"
        )
        
        # Build story (content)
        story = []
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1e40af'),
            spaceAfter=12,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#1e40af'),
            spaceAfter=8,
            spaceBefore=16,
            fontName='Helvetica-Bold'
        )
        
        subheading_style = ParagraphStyle(
            'CustomSubHeading',
            parent=styles['Heading3'],
            fontSize=11,
            textColor=colors.HexColor('#475569'),
            spaceAfter=6,
            spaceBefore=10,
            fontName='Helvetica-Bold'
        )
        
        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['Normal'],
            fontSize=10,
            textColor=colors.black,
            spaceAfter=6,
            leading=14
        )
        
        # ── Title Page ──────────────────────────────────────────────────────
        story.append(Spacer(1, 0.5 * inch))
        story.append(Paragraph(report_data['templateName'], title_style))
        story.append(Spacer(1, 0.2 * inch))
        
        # Workflow info
        info_data = [
            ['Workflow:', report_data['workflowName']],
            ['Report ID:', report_data['id']],
            ['Execution ID:', str(report_data['executionId'])],
            ['Generated:', datetime.now().strftime("%B %d, %Y at %H:%M UTC")],
            ['Status:', report_data['metrics'][0]['value'] if report_data['metrics'] else 'N/A']
        ]
        
        info_table = Table(info_data, colWidths=[2 * inch, 4 * inch])
        info_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
            ('ALIGN', (1, 0), (1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#475569')),
            ('TEXTCOLOR', (1, 0), (1, -1), colors.black),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(info_table)
        story.append(Spacer(1, 0.5 * inch))
        
        # ── Key Metrics ─────────────────────────────────────────────────────
        story.append(Paragraph("Key Metrics", heading_style))
        
        metrics_data = [['Metric', 'Value']]
        for metric in report_data.get('metrics', []):
            metrics_data.append([metric['key'], str(metric['value'])])
        
        if len(metrics_data) > 1:
            metrics_table = Table(metrics_data, colWidths=[3 * inch, 3 * inch])
            metrics_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 11),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f1f5f9')]),
            ]))
            story.append(metrics_table)
        
        story.append(Spacer(1, 0.3 * inch))
        
        # ── Executive Summary ───────────────────────────────────────────────
        exec_summary = report_data.get('executiveSummary', {})
        if exec_summary:
            story.append(Paragraph("Executive Summary", heading_style))
            
            for key, value in exec_summary.items():
                if value:
                    label = key.replace('_', ' ').replace('businessPurpose', 'Business Purpose').replace('keyFindings', 'Key Findings').replace('riskAssessment', 'Risk Assessment').replace('recommendation', 'Recommendation').replace('finalDecision', 'Final Decision')
                    story.append(Paragraph(f"<b>{label}:</b>", subheading_style))
                    story.append(Paragraph(str(value), body_style))
                    story.append(Spacer(1, 0.1 * inch))
        
        # ── Sections ────────────────────────────────────────────────────────
        sections = report_data.get('sections', {})
        for section_key, section_data in sections.items():
            if section_key == 'executive_summary':
                continue  # Already rendered
            
            if not section_data or (isinstance(section_data, (list, dict)) and not section_data):
                continue
            
            # Section title
            section_title = section_key.replace('_', ' ').title()
            story.append(Paragraph(section_title, heading_style))
            
            # Render section based on data type
            if isinstance(section_data, dict) and not isinstance(section_data, list):
                # Key-value pairs
                kv_data = [[k, str(v)] for k, v in section_data.items()]
                if kv_data:
                    kv_table = Table(kv_data, colWidths=[2.5 * inch, 3.5 * inch])
                    kv_table.setStyle(TableStyle([
                        ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
                        ('ALIGN', (1, 0), (1, -1), 'LEFT'),
                        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                        ('FONTSIZE', (0, 0), (-1, -1), 9),
                        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#475569')),
                    ]))
                    story.append(kv_table)
            elif isinstance(section_data, list):
                # List items
                for item in section_data:
                    story.append(Paragraph(f"• {str(item)}", body_style))
            else:
                # Plain text
                story.append(Paragraph(str(section_data), body_style))
            
            story.append(Spacer(1, 0.2 * inch))
        
        # ── Audit Trail ─────────────────────────────────────────────────────
        audit = report_data.get('audit', {})
        if audit:
            story.append(PageBreak())
            story.append(Paragraph("Audit Trail", heading_style))
            
            audit_data = [
                ['Execution ID:', str(audit.get('executionId', 'N/A'))],
                ['Workflow ID:', str(audit.get('workflowId', 'N/A'))],
                ['Timestamp:', audit.get('timestamp', 'N/A')],
                ['Triggered By:', audit.get('triggeredBy', 'N/A')],
                ['Duration:', audit.get('duration', 'N/A')],
                ['Node Count:', str(audit.get('nodeCount', 'N/A'))],
                ['AI Model:', audit.get('aiModel', 'N/A')],
                ['Validation Status:', audit.get('validationStatus', 'N/A')],
                ['Digital Fingerprint:', audit.get('digitalFingerprint', 'N/A')],
            ]
            
            audit_table = Table(audit_data, colWidths=[2.5 * inch, 3.5 * inch])
            audit_table.setStyle(TableStyle([
                ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
                ('ALIGN', (1, 0), (1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#475569')),
            ]))
            story.append(audit_table)
            
            # Audit logs
            audit_logs = audit.get('auditLog', [])
            if audit_logs:
                story.append(Spacer(1, 0.2 * inch))
                story.append(Paragraph("Recent Audit Logs:", subheading_style))
                for log in audit_logs[-10:]:  # Last 10 logs
                    story.append(Paragraph(f"• {log}", ParagraphStyle(
                        'LogStyle',
                        parent=body_style,
                        fontSize=8,
                        fontName='Courier'
                    )))
        
        # Build PDF
        def add_page_decorations(canvas, doc):
            PDFGeneratorService._add_header(canvas, doc, report_data)
            PDFGeneratorService._add_footer(canvas, doc, report_data)
        
        doc.build(story, onFirstPage=add_page_decorations, onLaterPages=add_page_decorations)
        
        # Get PDF bytes
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        logger.info(f"PDF generated successfully for report {report_data['id']}, size: {len(pdf_bytes)} bytes")
        return pdf_bytes
